name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5.4.3
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.0

  release:
    runs-on: ubuntu-latest
    environment: release
    if: github.ref == 'refs/heads/master'
    needs:
      - commitlint
      - lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        # https://github.com/relekang/python-semantic-release/releases
        uses: relekang/python-semantic-release@v7.34.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
      - name: Test release
        uses: python-semantic-release/python-semantic-release@v7.34.6
        if: github.ref_name != 'master'
        with:
          additional_options: --noop